In [1]:
import pandas as pd
from pathlib import Path
from sklearn.model_selection import train_test_split

base_path = Path("../../..")  # from src/mcq/preprocessing/
data_dir = base_path / "data" / "processed" / "mcq"

adhd_path = data_dir / "adhd_dataset.csv"
depression_path = data_dir / "depression_dataset.csv"
anxiety_path = data_dir / "anxiety_dataset.csv"
ocd_path = data_dir / "ocd_dataset.csv"

In [2]:
# Load all MCQ datasets and inspect basic structure

adhd_df = pd.read_csv(adhd_path)
depression_df = pd.read_csv(depression_path)
anxiety_df = pd.read_csv(anxiety_path)
ocd_df = pd.read_csv(ocd_path)

for name, df in {
    "ADHD": adhd_df,
    "Depression": depression_df,
    "Anxiety": anxiety_df,
    "OCD": ocd_df,
}.items():
    print(f"=== {name} dataset ===")
    print("Shape:", df.shape)
    print("Columns:", list(df.columns))
    display(df.head())
    print("\n")

=== ADHD dataset ===
Shape: (2000, 16)
Columns: ['q1', 'q2', 'q3', 'q4', 'q5', 'q6', 'q7', 'q8', 'q9', 'q10', 'q11', 'q12', 'q13', 'q14', 'q15', 'label']

   q1  q2  q3  q4  q5  q6  q7  q8  q9  q10  q11  q12  q13  q14  q15  label
0   3   1   3   2   3   2   3   3   3    2    3    2    3    2    2      1
1   1   0   0   1   0   1   1   1   1    0    2    0    1    0    0      0
2   2   1   3   2   1   2   2   3   3    3    1    3    2    3    2      1
3   0   2   1   1   0   1   1   0   2    1    0    0    1    0    2      0
4   3   3   2   3   3   2   3   2   2    1    2    2    3    3    3      1

=== Depression dataset ===
Shape: (2000, 16)
Columns: ['q1', 'q2', 'q3', 'q4', 'q5', 'q6', 'q7', 'q8', 'q9', 'q10', 'q11', 'q12', 'q13', 'q14', 'q15', 'label']

   q1  q2  q3  q4  q5  q6  q7  q8  q9  q10  q11  q12  q13  q14  q15  label
0   2   3   3   3   3   2   2   3   2    2    2    3    2    2    2      1
1   2   0   1   0   1   0   1   1   1    0    0    1    1    1    0      0
2   2   2   2   2   2   2   3   2   2    3    2    2    3    2    2      1
3   0   1   1   2   0   0   0   1   1    1    0    2    0    1    0      0
4   3   3   3   1   3   2   2   3   3    2    2    3    1    3    2      1

=== Anxiety dataset ===
Shape: (2000, 16)
Columns: ['q1', 'q2', 'q3', 'q4', 'q5', 'q6', 'q7', 'q8', 'q9', 'q10', 'q11', 'q12', 'q13', 'q14', 'q15', 'label']

   q1  q2  q3  q4  q5  q6  q7  q8  q9  q10  q11  q12  q13  q14  q15  label
0   3   2   2   2   1   2   3   1   3    3    2    3    3    2    2      1
1   1   1   2   1   0   0   0   1   0    0    0    1    0    1    1      0
2   3   2   2   1   1   3   1   1   1    2    1    2    3    3    2      1
3   0   1   0   0   1   1   2   0   0    1    1    1    2    0    1      0
4   3   1   2   2   3   2   3   2   2    2    1    2    3    2    3      1

=== OCD dataset ===
Shape: (2000, 16)
Columns: ['q1', 'q2', 'q3', 'q4', 'q5', 'q6', 'q7', 'q8', 'q9', 'q10', 'q11', 'q12', 'q13', 'q14', 'q15', 'label']

   q1  q2  q3  q4  q5  q6  q7  q8  q9  q10  q11  q12  q13  q14  q15  label
0   1   2   2   2   2   2   2   1   3    3    3    1    2    2    3      1
1   0   0   0   0   0   2   1   0   1    2    1    1    1    1    0      0
2   3   2   2   1   3   3   1   3   2    2    2    3    2    3    3      1
3   0   0   0   1   1   0   1   0   1    1    2    0    0    1    0      0
4   2   2   3   1   2   2   1   1   3    3    3    3    2    3    3      1

In [3]:
# Check missing values (NaN) and -1 placeholders per dataset

def summarize_missing(df, name: str):
    print(f"=== {name} missing summary ===")
    print("NaN per column:\n", df.isna().sum())
    # Treat -1 as missing value in features
    feature_cols = [c for c in df.columns if c != "label"]
    minus_one_counts = (df[feature_cols] == -1).sum()
    print("\n-1 per feature (treated as missing):\n", minus_one_counts)
    print("Total rows:", len(df))
    print("\n")

summarize_missing(adhd_df, "ADHD")
summarize_missing(depression_df, "Depression")
summarize_missing(anxiety_df, "Anxiety")
summarize_missing(ocd_df, "OCD")

=== ADHD missing summary ===
NaN per column:
 q1       0
q2       0
q3       0
q4       0
q5       0
q6       0
q7       0
q8       0
q9       0
q10      0
q11      0
q12      0
q13      0
q14      0
q15      0
label    0
dtype: int64

-1 per feature (treated as missing):
 q1     0
q2     0
q3     0
q4     0
q5     0
q6     0
q7     0
q8     0
q9     0
q10    0
q11    0
q12    0
q13    0
q14    0
q15    0
dtype: int64
Total rows: 2000


=== Depression missing summary ===
NaN per column:
 q1       0
q2       0
q3       0
q4       0
q5       0
q6       0
q7       0
q8       0
q9       0
q10      0
q11      0
q12      0
q13      0
q14      0
q15      0
label    0
dtype: int64

-1 per feature (treated as missing):
 q1     0
q2     0
q3     0
q4     0
q5     0
q6     0
q7     0
q8     0
q9     0
q10    0
q11    0
q12    0
q13    0
q14    0
q15    0
dtype: int64
Total rows: 2000


=== Anxiety missing summary ===
NaN per column:
 q1       0
q2       0
q3       0
q4       0
q5       0
q6       0
q7       0
q8       0
q9       0
q10      0
q11      0
q12      0
q13      0
q14      0
q15      0
label    0
dtype: int64

-1 per feature (treated as missing):
 q1     0
q2     0
q3     0
q4     0
q5     0
q6     0
q7     0
q8     0
q9     0
q10    0
q11    0
q12    0
q13    0
q14    0
q15    0
dtype: int64
Total rows: 2000


=== OCD missing summary ===
NaN per column:
 q1       0
q2       0
q3       0
q4       0
q5       0
q6       0
q7       0
q8       0
q9       0
q10      0
q11      0
q12      0
q13      0
q14      0
q15      0
label    0
dtype: int64

-1 per feature (treated as missing):
 q1     0
q2     0
q3     0
q4     0
q5     0
q6     0
q7     0
q8     0
q9     0
q10    0
q11    0
q12    0
q13    0
q14    0
q15    0
dtype: int64
Total rows: 2000

In [5]:
# Handle missing values: convert -1 to NaN and impute with column medians (per disease)

from copy import deepcopy
import numpy as np

clean_datasets = {}

for name, df in {
    "adhd": adhd_df,
    "depression": depression_df,
    "anxiety": anxiety_df,
    "ocd": ocd_df,
}.items():
    df_clean = deepcopy(df)
    feature_cols = [c for c in df_clean.columns if c != "label"]

    # Replace -1 with NaN in feature columns
    df_clean[feature_cols] = df_clean[feature_cols].replace(-1, np.nan)

    # Impute NaN with column median for each feature
    medians = df_clean[feature_cols].median()
    df_clean[feature_cols] = df_clean[feature_cols].fillna(medians)

    clean_datasets[name] = df_clean

for name, df_clean in clean_datasets.items():
    print(f"{name}: any remaining NaN?", df_clean.isna().any().any())

adhd: any remaining NaN? False
depression: any remaining NaN? False
anxiety: any remaining NaN? False
ocd: any remaining NaN? False

In [6]:
# Split into features (X) and labels (y) for each disease

XY_splits = {}

for name, df_clean in clean_datasets.items():
    X = df_clean.drop(columns=["label"])
    y = df_clean["label"]
    XY_splits[name] = (X, y)
    print(f"{name}: X shape = {X.shape}, y shape = {y.shape}")

adhd: X shape = (2000, 15), y shape = (2000,)
depression: X shape = (2000, 15), y shape = (2000,)
anxiety: X shape = (2000, 15), y shape = (2000,)
ocd: X shape = (2000, 15), y shape = (2000,)

In [7]:
# Train/test split for each disease-specific dataset

train_test_splits = {}

for name, (X, y) in XY_splits.items():
    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.2,
        random_state=42,
        stratify=y,
    )
    train_test_splits[name] = {
        "X_train": X_train,
        "X_test": X_test,
        "y_train": y_train,
        "y_test": y_test,
    }
    print(
        f"{name}: X_train={X_train.shape}, X_test={X_test.shape}, "
        f"y_train={y_train.shape}, y_test={y_test.shape}"
    )

adhd: X_train=(1600, 15), X_test=(400, 15), y_train=(1600,), y_test=(400,)
depression: X_train=(1600, 15), X_test=(400, 15), y_train=(1600,), y_test=(400,)
anxiety: X_train=(1600, 15), X_test=(400, 15), y_train=(1600,), y_test=(400,)
ocd: X_train=(1600, 15), X_test=(400, 15), y_train=(1600,), y_test=(400,)

In [8]:
# Define models for MCQ classification per disease

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix

# We'll use the already-prepared XY_splits (per disease) from previous cells.

estimators = {
    "logreg": lambda: LogisticRegression(max_iter=1000, n_jobs=-1),
    "rf": lambda: RandomForestClassifier(n_estimators=200, random_state=42, n_jobs=-1),
    "xgb": lambda: XGBClassifier(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=4,
        subsample=0.9,
        colsample_bytree=0.9,
        objective="binary:logistic",
        eval_metric="logloss",
        n_jobs=-1,
        random_state=42,
    ),
}

In [9]:
# Train logistic regression, XGBoost, and Random Forest with 5-fold CV for each disease

cv_results = {}
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

for disease_name, (X, y) in XY_splits.items():
    print(f"\n===== Disease: {disease_name} =====")
    cv_results[disease_name] = {}
    for algo_name, make_est in estimators.items():
        model = make_est()
        acc_scores = cross_val_score(model, X, y, cv=cv, scoring="accuracy", n_jobs=-1)
        f1_scores = cross_val_score(model, X, y, cv=cv, scoring="f1_macro", n_jobs=-1)
        cv_results[disease_name][algo_name] = {
            "accuracy_mean": acc_scores.mean(),
            "accuracy_std": acc_scores.std(),
            "f1_macro_mean": f1_scores.mean(),
            "f1_macro_std": f1_scores.std(),
        }
        print(
            f"{algo_name}: "
            f"acc={acc_scores.mean():.3f}±{acc_scores.std():.3f}, "
            f"f1_macro={f1_scores.mean():.3f}±{f1_scores.std():.3f}"
        )

===== Disease: adhd =====
logreg: acc=1.000±0.000, f1_macro=1.000±0.000
rf: acc=1.000±0.000, f1_macro=1.000±0.000
xgb: acc=1.000±0.001, f1_macro=0.999±0.001

===== Disease: depression =====
logreg: acc=1.000±0.000, f1_macro=1.000±0.000
rf: acc=1.000±0.000, f1_macro=1.000±0.000
xgb: acc=1.000±0.000, f1_macro=1.000±0.000

===== Disease: anxiety =====
logreg: acc=1.000±0.000, f1_macro=1.000±0.000
rf: acc=1.000±0.000, f1_macro=1.000±0.000
xgb: acc=1.000±0.000, f1_macro=1.000±0.000

===== Disease: ocd =====
logreg: acc=1.000±0.000, f1_macro=1.000±0.000
rf: acc=1.000±0.000, f1_macro=1.000±0.000
xgb: acc=1.000±0.000, f1_macro=1.000±0.000

In [10]:
# Fit final models on full training data and evaluate on held-out test sets

fitted_models = {}

for disease_name, splits in train_test_splits.items():
    print(f"\n===== Final evaluation for {disease_name} =====")
    X_train = splits["X_train"]
    X_test = splits["X_test"]
    y_train = splits["y_train"]
    y_test = splits["y_test"]

    fitted_models[disease_name] = {}
    for algo_name, make_est in estimators.items():
        model = make_est()
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)

        acc = accuracy_score(y_test, y_pred)
        f1 = f1_score(y_test, y_pred, average="macro")
        print(f"\nModel: {algo_name}")
        print(f"Accuracy: {acc:.3f}, Macro-F1: {f1:.3f}")
        print("Classification report:\n", classification_report(y_test, y_pred))
        print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))

        fitted_models[disease_name][algo_name] = model

===== Final evaluation for adhd =====

Model: logreg
Accuracy: 1.000, Macro-F1: 1.000
Classification report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       200
           1       1.00      1.00      1.00       200

    accuracy                           1.00       400
   macro avg       1.00      1.00      1.00       400
weighted avg       1.00      1.00      1.00       400

Confusion matrix:
 [[200   0]
 [  0 200]]

e:\Interview-AI-Detection\interview-ai-detection\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1184: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)

Model: rf
Accuracy: 1.000, Macro-F1: 1.000
Classification report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       200
           1       1.00      1.00      1.00       200

    accuracy                           1.00       400
   macro avg       1.00      1.00      1.00       400
weighted avg       1.00      1.00      1.00       400

Confusion matrix:
 [[200   0]
 [  0 200]]

Model: xgb
Accuracy: 1.000, Macro-F1: 1.000
Classification report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       200
           1       1.00      1.00      1.00       200

    accuracy                           1.00       400
   macro avg       1.00      1.00      1.00       400
weighted avg       1.00      1.00      1.00       400

Confusion matrix:
 [[200   0]
 [  0 200]]

===== Final evaluation for depression =====

Model: logreg
Accuracy: 1.000, Macro-F1: 1.000
Classification report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       200
           1       1.00      1.00      1.00       200

    accuracy                           1.00       400
   macro avg       1.00      1.00      1.00       400
weighted avg       1.00      1.00      1.00       400

Confusion matrix:
 [[200   0]
 [  0 200]]

e:\Interview-AI-Detection\interview-ai-detection\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1184: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)

Model: rf
Accuracy: 1.000, Macro-F1: 1.000
Classification report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       200
           1       1.00      1.00      1.00       200

    accuracy                           1.00       400
   macro avg       1.00      1.00      1.00       400
weighted avg       1.00      1.00      1.00       400

Confusion matrix:
 [[200   0]
 [  0 200]]

Model: xgb
Accuracy: 1.000, Macro-F1: 1.000
Classification report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       200
           1       1.00      1.00      1.00       200

    accuracy                           1.00       400
   macro avg       1.00      1.00      1.00       400
weighted avg       1.00      1.00      1.00       400

Confusion matrix:
 [[200   0]
 [  0 200]]

===== Final evaluation for anxiety =====

Model: logreg
Accuracy: 1.000, Macro-F1: 1.000
Classification report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       200
           1       1.00      1.00      1.00       200

    accuracy                           1.00       400
   macro avg       1.00      1.00      1.00       400
weighted avg       1.00      1.00      1.00       400

Confusion matrix:
 [[200   0]
 [  0 200]]

e:\Interview-AI-Detection\interview-ai-detection\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1184: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)

Model: rf
Accuracy: 1.000, Macro-F1: 1.000
Classification report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       200
           1       1.00      1.00      1.00       200

    accuracy                           1.00       400
   macro avg       1.00      1.00      1.00       400
weighted avg       1.00      1.00      1.00       400

Confusion matrix:
 [[200   0]
 [  0 200]]

Model: xgb
Accuracy: 1.000, Macro-F1: 1.000
Classification report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       200
           1       1.00      1.00      1.00       200

    accuracy                           1.00       400
   macro avg       1.00      1.00      1.00       400
weighted avg       1.00      1.00      1.00       400

Confusion matrix:
 [[200   0]
 [  0 200]]

===== Final evaluation for ocd =====

Model: logreg
Accuracy: 1.000, Macro-F1: 1.000
Classification report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       200
           1       1.00      1.00      1.00       200

    accuracy                           1.00       400
   macro avg       1.00      1.00      1.00       400
weighted avg       1.00      1.00      1.00       400

Confusion matrix:
 [[200   0]
 [  0 200]]

e:\Interview-AI-Detection\interview-ai-detection\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1184: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)

Model: rf
Accuracy: 1.000, Macro-F1: 1.000
Classification report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       200
           1       1.00      1.00      1.00       200

    accuracy                           1.00       400
   macro avg       1.00      1.00      1.00       400
weighted avg       1.00      1.00      1.00       400

Confusion matrix:
 [[200   0]
 [  0 200]]

Model: xgb
Accuracy: 1.000, Macro-F1: 1.000
Classification report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       200
           1       1.00      1.00      1.00       200

    accuracy                           1.00       400
   macro avg       1.00      1.00      1.00       400
weighted avg       1.00      1.00      1.00       400

Confusion matrix:
 [[200   0]
 [  0 200]]

In [12]:
# Compute and display feature importance for each model (which questions matter most)

import numpy as np

feature_importances = {}

for disease_name, models in fitted_models.items():
    print(f"\n===== Feature importance for {disease_name} =====")
    X_example, _ = XY_splits[disease_name]
    feature_names = list(X_example.columns)

    feature_importances[disease_name] = {}

    for algo_name, model in models.items():
        if algo_name == "logreg":
            # Use absolute coefficient magnitude as importance
            coefs = np.abs(model.coef_)
            if coefs.ndim == 2:
                importances = coefs.mean(axis=0)
            else:
                importances = coefs
        else:
            # Tree-based models expose feature_importances_
            importances = getattr(model, "feature_importances_", None)

        if importances is None:
            print(f"{algo_name}: no feature_importances_ available")
            continue

        importance_pairs = sorted(
            zip(feature_names, importances), key=lambda x: x[1], reverse=True
        )
        feature_importances[disease_name][algo_name] = importance_pairs

        print(f"\nTop features for {algo_name}:")
        for fname, score in importance_pairs[:10]:
            print(f"  {fname}: {score:.4f}")

===== Feature importance for adhd =====

Top features for logreg:
  q12: 0.8993
  q1: 0.8585
  q8: 0.8442
  q5: 0.8221
  q13: 0.8097
  q6: 0.7948
  q10: 0.7916
  q7: 0.7550
  q15: 0.7544
  q9: 0.7307

Top features for rf:
  q5: 0.0974
  q1: 0.0933
  q13: 0.0919
  q15: 0.0870
  q2: 0.0860
  q9: 0.0708
  q8: 0.0693
  q14: 0.0647
  q10: 0.0636
  q3: 0.0547

Top features for xgb:
  q9: 0.1289
  q13: 0.1088
  q1: 0.1053
  q2: 0.1036
  q5: 0.0929
  q15: 0.0737
  q10: 0.0554
  q8: 0.0535
  q3: 0.0512
  q6: 0.0491

===== Feature importance for depression =====

Top features for logreg:
  q6: 0.8924
  q3: 0.8431
  q1: 0.8426
  q5: 0.8279
  q8: 0.7633
  q9: 0.7472
  q7: 0.7466
  q12: 0.7388
  q4: 0.7360
  q2: 0.7315

Top features for rf:
  q3: 0.1401
  q2: 0.1050
  q9: 0.1027
  q12: 0.0811
  q15: 0.0780
  q14: 0.0734
  q1: 0.0649
  q8: 0.0631
  q11: 0.0609
  q7: 0.0587

Top features for xgb:
  q3: 0.1528
  q2: 0.1234
  q12: 0.1158
  q15: 0.1037
  q9: 0.0936
  q8: 0.0655
  q7: 0.0574
  q1: 0.0497
  q11: 0.0430
  q14: 0.0383

===== Feature importance for anxiety =====

Top features for logreg:
  q2: 0.8777
  q15: 0.8722
  q4: 0.8458
  q3: 0.8122
  q13: 0.8037
  q5: 0.7987
  q14: 0.7830
  q8: 0.7550
  q9: 0.7538
  q6: 0.7522

Top features for rf:
  q1: 0.1455
  q14: 0.0904
  q15: 0.0884
  q4: 0.0816
  q13: 0.0780
  q10: 0.0697
  q11: 0.0634
  q3: 0.0633
  q12: 0.0593
  q5: 0.0511

Top features for xgb:
  q1: 0.2188
  q14: 0.1166
  q13: 0.0889
  q15: 0.0858
  q12: 0.0679
  q3: 0.0645
  q4: 0.0627
  q10: 0.0539
  q8: 0.0513
  q7: 0.0380

===== Feature importance for ocd =====

Top features for logreg:
  q5: 0.9308
  q12: 0.8436
  q7: 0.8404
  q3: 0.7822
  q10: 0.7689
  q1: 0.7341
  q13: 0.7312
  q6: 0.7254
  q4: 0.7235
  q2: 0.7191

Top features for rf:
  q2: 0.1180
  q7: 0.1118
  q12: 0.1113
  q5: 0.0843
  q1: 0.0795
  q15: 0.0638
  q6: 0.0583
  q13: 0.0559
  q4: 0.0548
  q11: 0.0527

Top features for xgb:
  q2: 0.2707
  q7: 0.1445
  q12: 0.1337
  q5: 0.0615
  q10: 0.0562
  q15: 0.0500
  q1: 0.0493
  q13: 0.0426
  q6: 0.0426
  q9: 0.0334

In [13]:
# Persist trained models to disk under models/mcq_model

import joblib

models_dir = base_path / "models" / "mcq_model"
models_dir.mkdir(parents=True, exist_ok=True)

for disease_name, models in fitted_models.items():
    for algo_name, model in models.items():
        model_path = models_dir / f"{disease_name}_{algo_name}.joblib"
        joblib.dump(model, model_path)
        print(f"Saved {disease_name} - {algo_name} model to {model_path}")

Saved adhd - logreg model to ..\..\..\models\mcq_model\adhd_logreg.joblib
Saved adhd - rf model to ..\..\..\models\mcq_model\adhd_rf.joblib
Saved adhd - xgb model to ..\..\..\models\mcq_model\adhd_xgb.joblib
Saved depression - logreg model to ..\..\..\models\mcq_model\depression_logreg.joblib
Saved depression - rf model to ..\..\..\models\mcq_model\depression_rf.joblib
Saved depression - xgb model to ..\..\..\models\mcq_model\depression_xgb.joblib
Saved anxiety - logreg model to ..\..\..\models\mcq_model\anxiety_logreg.joblib
Saved anxiety - rf model to ..\..\..\models\mcq_model\anxiety_rf.joblib
Saved anxiety - xgb model to ..\..\..\models\mcq_model\anxiety_xgb.joblib
Saved ocd - logreg model to ..\..\..\models\mcq_model\ocd_logreg.joblib
Saved ocd - rf model to ..\..\..\models\mcq_model\ocd_rf.joblib
Saved ocd - xgb model to ..\..\..\models\mcq_model\ocd_xgb.joblib